# Setup
title:        "1tona"
tagline:      "okazjonalny transport do 1 tony"
baseurl:      ""
locale:       "pl"

# About/contact
author:
  name:       "Łukasz Lanart"
  url:        "https://lenart.org.pl"

#Others
markdown: kramdown
